### ISSUE TITLE
SLIDE release checklist 

### ISSUE THREAD

**Issue by stufield** [stufield/TestPkg#1]
# Prepare for release
 
* [x] Check that all desired branches are merged
* [ ] Run in SLIDE:
```r
devtools::check(document = FALSE, 
                vignettes = FALSE,
                env_vars = c(ON_JENKINS = "true",
                             NOT_CRAN   = "true",
                             TZ         = "America/Denver"))
```
* [ ]  Run:
```bash
glog -10    # decide which semantic version to use
```
[semantic version system](https://semver.org)
* [ ] Run:
```bash
# choices are: 'major', 'minor', 'patch'
Rscript --vanilla -e "somaverse::init_release(ver = 'minor')"
```
* [ ] Edit `NEWS.md` file
* [ ] Run:
```bash
# ensure no spelling errors introduced in the NEWS.md
Rscript --vanilla -e "devtools::spell_check()"
```
* [ ] Run
```bash
Rscript --vanilla -e "somaverse::push_release()"
```
* [ ] Run
```bash
make pkgdown
```
* [ ] Run
```bash
Rscript --vanilla -e "somaverse::bump_to_dev()"
```

-------------------

**Core Packages**:
* [ ] `SomaReadr`
* [ ] `SomaGlobals`
* [ ] `SomaPlyr`
* [ ] `SomaPlot`
* [ ] `SomaClassify`
* [ ] `SomaSurvival`
* [ ] `palantir`
------------------------
**Non-core**:
* [x] `SomaPCA`
* [ ] `SomaNormalization`
* [ ] `SomaStabilitySelection`
* [x] `SomaMixedEffects`
-----------------------
**Independent-pkgs**:
* [x] `SomaDB`
-----------------------
**AppMod-pkgs**:
* [ ] `SomaPipeline`
* [ ] `SomaModelAssessment`
* [ ] `SomaModelChange`
* [ ] `SMAdata`
-----------------------
**Meta-pkgs**:
* [ ] `somaverse`
-----------------------
**Semi-stale-pkgs**:
* [x] `SomaFeatureSelect`
* [x] `SomaBiomarkers`

**Comment by stufield** [comment]
**0.4.8 release**:
 
* [x] `SomaReadr`
* [x] `SomaGlobals`
* [x] `SomaSurvival`
* [x] `SomaPipeline`
* [x] `SomaPlyr`
* [x] `SomaNormalization`
* [x] `SomaPlot`
* [x] `SomaClassify`
* [x] `SomaStabilitySelection`
* [x] `SomaPCA`
* [x] `SomaDB`
* [x] `somaverse`
* [x] `LeedsPredict`
* [x] `SomaMixedEffects`
* [x] `SomaFeatureSelect`
